<%@ Page Title="Create New Receipt" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageEmpRole.aspx.cs" Inherits="ESCARE.ManageEmpRole" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <script>
        $(document).ready(function () {
            if ($("#hdnDdlOldValue").val() != $("#DropDownList2").val()) {
                DropdwonOnChangeFunction();
            }
        });
    </script>
    <div class="jumbotron">
        <div id="wrapper">
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                <ContentTemplate>
                    <table align="center">
                        <tr>
                            <td class="auto-style3" align="right">
                                <asp:Label ID="lblEmpName" runat="server" Text="Employee:"></asp:Label>
                            </td>
                            <td class="auto-style4" style="width: 187px">
                                <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="true" CausesValidation="false" DataSourceID="SqlDataSource2" DataTextField="Name" DataValueField="EID" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" AppendDataBoundItems="True">
                                
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="select EID, (FName+' '+LName) AS Name from Employees where Profition =3 or Profition = 4"></asp:SqlDataSource>
                            </td>
                            <td class="auto-style3" align="right">
                                <asp:Label ID="lblEmpID" runat="server" Text="ID:"></asp:Label>
                            </td>
                            <td class="auto-style4">
                                <asp:TextBox ID="txtEmpID" runat="server" placeholder="" Width="142px" ReadOnly="True" AutoPostBack="True" OnTextChanged="txtEmpID_TextChanged"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                <asp:Label ID="ClID" runat="server" Text="Clinic ID:"></asp:Label>
                            </td>
                            <td class="auto-style5" style="width: 187px">
                                <asp:TextBox ID="txtCLID" runat="server" Width="142px" placeholder="01"></asp:TextBox>
                            </td>
                            <td align="right">
                                &nbsp;</td>
                            <td class="auto-style2">
                                <asp:Button ID="btnEmpAdd" runat="server" OnClick="btnPAdd_Click" Text="Save Services" />
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                <asp:Label ID="lblServices" runat="server" Text="Services:"></asp:Label>
                            </td>
                            <td colspan="4" align="center">

                                <asp:CheckBoxList ID="chkServices" runat="server" DataSourceID="SqlDataSource1" DataTextField="Name" DataValueField="SID" RepeatLayout="Flow">
                                </asp:CheckBoxList>
                                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [SID], [Name] FROM [Services]"></asp:SqlDataSource>

                            </td>
                        </tr>
                        <tr>
                            <td colspan="1" align="center">
                                &nbsp;</td>
                            <td colspan="4" align="center">
                                
                            </td>
                            <td colspan="1" align="center">
                                &nbsp;</td>
                        </tr>
                        <tr>
                            <td colspan="4" align="center" style="height: 42px">
                                <br />
                                <asp:Label ID="lblmsg" runat="server" Text=""></asp:Label>
                            </td>
                        </tr>
                        <tr >
                            <td colspan="4" align="center">
                                <asp:GridView ID="gvEmpService" runat="server" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" AllowCustomPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" PageSize="5">
                                    <AlternatingRowStyle BackColor="#CCCCCC" />
                                    <FooterStyle BackColor="#CCCCCC" />
                                    <HeaderStyle BackColor="#101010" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                    <SortedAscendingHeaderStyle BackColor="#808080" />
                                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                    <SortedDescendingHeaderStyle BackColor="#383838" />
                                </asp:GridView>
                            </td>
                        </tr>
                    </table>
                </ContentTemplate>

            </asp:UpdatePanel>
            
        </div>
    </div>
    <div class="row">
    </div>

</asp:Content>
